---
- name: test if our repo is ok
  hosts: localhost

  tasks:
    - assert:
        that:
          -  "{{ lookup( 'file', '/var/lib/jenkins/workspace/callback-plugin-ci/git/git/to_be_tested.txt') }} ==  0"
